# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e238213a3e55e8a769384c8390764450055deba9b91371eb0615b6845df7bf99198915bd2139f1719b68452d8fb6ead7fe877d31fd5de5008d675b76959b0ff3

test:
  secret_key_base: c07c74457f03efbf2269992fcc5bdb56f77c2ce2e948a25cab1940c6739d7d4d66197b950c99dbd2687b8556c23171883d5b7e4b56d77986c4fc7c1a9c92317d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
